{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "74e8e06d",
   "metadata": {},
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3f491bbe",
   "metadata": {},
   "source": [
    "Its recommended to create a custom exception by defining a new class that inherits from 'Exception' class because it serves as the base class for all\n",
    "exceptions,and provide a common way to handle exceptions.\n",
    "\n",
    "By using custom exception class, you can create specific exception types that can be raised and caught in a specific way, that makes our code more structured and easy to understand and maintain"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "02e72e57",
   "metadata": {},
   "source": [
    "Q2. Write a python program to print Python Exception Hierarchy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "cdc0d595-0d5d-4140-8f92-4dcde506f05d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'Exception'>\n",
      "<class 'TypeError'>\n",
      "<class 'decimal.FloatOperation'>\n",
      "<class 'email.errors.MultipartConversionError'>\n",
      "<class 'StopAsyncIteration'>\n",
      "<class 'StopIteration'>\n",
      "<class 'ImportError'>\n",
      "<class 'ModuleNotFoundError'>\n",
      "<class 'zipimport.ZipImportError'>\n",
      "<class 'OSError'>\n",
      "<class 'ConnectionError'>\n",
      "<class 'BrokenPipeError'>\n",
      "<class 'ConnectionAbortedError'>\n",
      "<class 'ConnectionRefusedError'>\n",
      "<class 'ConnectionResetError'>\n",
      "<class 'http.client.RemoteDisconnected'>\n",
      "<class 'BlockingIOError'>\n",
      "<class 'ChildProcessError'>\n",
      "<class 'FileExistsError'>\n",
      "<class 'FileNotFoundError'>\n",
      "<class 'IsADirectoryError'>\n",
      "<class 'NotADirectoryError'>\n",
      "<class 'InterruptedError'>\n",
      "<class 'zmq.error.InterruptedSystemCall'>\n",
      "<class 'PermissionError'>\n",
      "<class 'ProcessLookupError'>\n",
      "<class 'TimeoutError'>\n",
      "<class 'io.UnsupportedOperation'>\n",
      "<class 'signal.itimer_error'>\n",
      "<class 'socket.herror'>\n",
      "<class 'socket.gaierror'>\n",
      "<class 'ssl.SSLError'>\n",
      "<class 'ssl.SSLCertVerificationError'>\n",
      "<class 'ssl.SSLZeroReturnError'>\n",
      "<class 'ssl.SSLWantWriteError'>\n",
      "<class 'ssl.SSLWantReadError'>\n",
      "<class 'ssl.SSLSyscallError'>\n",
      "<class 'ssl.SSLEOFError'>\n",
      "<class 'shutil.Error'>\n",
      "<class 'shutil.SameFileError'>\n",
      "<class 'shutil.SpecialFileError'>\n",
      "<class 'shutil.ExecError'>\n",
      "<class 'shutil.ReadError'>\n",
      "<class 'urllib.error.URLError'>\n",
      "<class 'urllib.error.HTTPError'>\n",
      "<class 'urllib.error.ContentTooShortError'>\n",
      "<class 'gzip.BadGzipFile'>\n",
      "<class 'EOFError'>\n",
      "<class 'asyncio.exceptions.IncompleteReadError'>\n",
      "<class 'RuntimeError'>\n",
      "<class 'RecursionError'>\n",
      "<class 'NotImplementedError'>\n",
      "<class 'zmq.error.ZMQVersionError'>\n",
      "<class 'IPython.core.error.StdinNotImplementedError'>\n",
      "<class '_frozen_importlib._DeadlockError'>\n",
      "<class 'threading.BrokenBarrierError'>\n",
      "<class 'concurrent.futures._base.BrokenExecutor'>\n",
      "<class 'concurrent.futures.thread.BrokenThreadPool'>\n",
      "<class 'asyncio.exceptions.SendfileNotAvailableError'>\n",
      "<class 'pkg_resources.ExtractionError'>\n",
      "<class '_pydevd_bundle.pydevd_vars.VariableError'>\n",
      "<class 'NameError'>\n",
      "<class 'UnboundLocalError'>\n",
      "<class 'AttributeError'>\n",
      "<class 'dataclasses.FrozenInstanceError'>\n",
      "<class 'SyntaxError'>\n",
      "<class 'IndentationError'>\n",
      "<class 'TabError'>\n",
      "<class 'LookupError'>\n",
      "<class 'IndexError'>\n",
      "<class 'KeyError'>\n",
      "<class 'jupyter_client.kernelspec.NoSuchKernel'>\n",
      "<class 'IPython.terminal.pt_inputhooks.UnknownBackend'>\n",
      "<class 'encodings.CodecRegistryError'>\n",
      "<class 'ValueError'>\n",
      "<class 'UnicodeError'>\n",
      "<class 'UnicodeEncodeError'>\n",
      "<class 'UnicodeDecodeError'>\n",
      "<class 'UnicodeTranslateError'>\n",
      "<class 'io.UnsupportedOperation'>\n",
      "<class 'json.decoder.JSONDecodeError'>\n",
      "<class 'ssl.SSLCertVerificationError'>\n",
      "<class 'binascii.Error'>\n",
      "<class '_hashlib.UnsupportedDigestmodError'>\n",
      "<class 'calendar.IllegalMonthError'>\n",
      "<class 'calendar.IllegalWeekdayError'>\n",
      "<class 'dateutil.parser._parser.ParserError'>\n",
      "<class 'pygments.util.ClassNotFound'>\n",
      "<class 'IPython.lib.clipboard.ClipboardEmpty'>\n",
      "<class 'email.errors.MessageDefect'>\n",
      "<class 'email.errors.NoBoundaryInMultipartDefect'>\n",
      "<class 'email.errors.StartBoundaryNotFoundDefect'>\n",
      "<class 'email.errors.CloseBoundaryNotFoundDefect'>\n",
      "<class 'email.errors.FirstHeaderLineIsContinuationDefect'>\n",
      "<class 'email.errors.MisplacedEnvelopeHeaderDefect'>\n",
      "<class 'email.errors.MissingHeaderBodySeparatorDefect'>\n",
      "<class 'email.errors.MultipartInvariantViolationDefect'>\n",
      "<class 'email.errors.InvalidMultipartContentTransferEncodingDefect'>\n",
      "<class 'email.errors.UndecodableBytesDefect'>\n",
      "<class 'email.errors.InvalidBase64PaddingDefect'>\n",
      "<class 'email.errors.InvalidBase64CharactersDefect'>\n",
      "<class 'email.errors.InvalidBase64LengthDefect'>\n",
      "<class 'email.errors.HeaderDefect'>\n",
      "<class 'email.errors.InvalidHeaderDefect'>\n",
      "<class 'email.errors.HeaderMissingRequiredValue'>\n",
      "<class 'email.errors.NonPrintableDefect'>\n",
      "<class 'email.errors.ObsoleteHeaderDefect'>\n",
      "<class 'email.errors.NonASCIILocalPartDefect'>\n",
      "<class 'email.errors.InvalidDateDefect'>\n",
      "<class 'IPython.core.magics.code.MacroToEdit'>\n",
      "<class 'plistlib.InvalidFileException'>\n",
      "<class 'pkg_resources._vendor.more_itertools.more.UnequalIterablesError'>\n",
      "<class 'pkg_resources.extern.packaging.version.InvalidVersion'>\n",
      "<class 'pkg_resources._vendor.packaging._manylinux._ELFFileHeader._InvalidELFFileHeader'>\n",
      "<class 'pkg_resources.extern.packaging.utils.InvalidWheelFilename'>\n",
      "<class 'pkg_resources.extern.packaging.utils.InvalidSdistFilename'>\n",
      "<class 'pkg_resources.extern.packaging.specifiers.InvalidSpecifier'>\n",
      "<class 'pkg_resources.extern.packaging.markers.InvalidMarker'>\n",
      "<class 'pkg_resources.extern.packaging.markers.UndefinedComparison'>\n",
      "<class 'pkg_resources.extern.packaging.markers.UndefinedEnvironmentName'>\n",
      "<class 'pkg_resources.extern.packaging.requirements.InvalidRequirement'>\n",
      "<class 'pkg_resources.RequirementParseError'>\n",
      "<class 'packaging.version.InvalidVersion'>\n",
      "<class 'AssertionError'>\n",
      "<class 'ArithmeticError'>\n",
      "<class 'FloatingPointError'>\n",
      "<class 'OverflowError'>\n",
      "<class 'ZeroDivisionError'>\n",
      "<class 'decimal.DivisionByZero'>\n",
      "<class 'decimal.DivisionUndefined'>\n",
      "<class 'decimal.DecimalException'>\n",
      "<class 'decimal.Clamped'>\n",
      "<class 'decimal.Rounded'>\n",
      "<class 'decimal.Underflow'>\n",
      "<class 'decimal.Overflow'>\n",
      "<class 'decimal.Inexact'>\n",
      "<class 'decimal.Underflow'>\n",
      "<class 'decimal.Overflow'>\n",
      "<class 'decimal.Subnormal'>\n",
      "<class 'decimal.Underflow'>\n",
      "<class 'decimal.DivisionByZero'>\n",
      "<class 'decimal.FloatOperation'>\n",
      "<class 'decimal.InvalidOperation'>\n",
      "<class 'decimal.ConversionSyntax'>\n",
      "<class 'decimal.DivisionImpossible'>\n",
      "<class 'decimal.DivisionUndefined'>\n",
      "<class 'decimal.InvalidContext'>\n",
      "<class 'SystemError'>\n",
      "<class 'encodings.CodecRegistryError'>\n",
      "<class 'ReferenceError'>\n",
      "<class 'MemoryError'>\n",
      "<class 'BufferError'>\n",
      "<class 'Warning'>\n",
      "<class 'UserWarning'>\n",
      "<class 'getpass.GetPassWarning'>\n",
      "<class 'IPython.core.formatters.FormatterWarning'>\n",
      "<class 'EncodingWarning'>\n",
      "<class 'DeprecationWarning'>\n",
      "<class 'IPython.core.interactiveshell.ProvisionalWarning'>\n",
      "<class 'PendingDeprecationWarning'>\n",
      "<class 'SyntaxWarning'>\n",
      "<class 'RuntimeWarning'>\n",
      "<class 'zmq.asyncio.ProactorSelectorThreadWarning'>\n",
      "<class 'dateutil.parser._parser.UnknownTimezoneWarning'>\n",
      "<class 'pkg_resources.PEP440Warning'>\n",
      "<class 'FutureWarning'>\n",
      "<class 'IPython.core.completer.ProvisionalCompleterWarning'>\n",
      "<class 'ImportWarning'>\n",
      "<class 'UnicodeWarning'>\n",
      "<class 'BytesWarning'>\n",
      "<class 'ResourceWarning'>\n",
      "<class 'dateutil.tz.DeprecatedTzFormatWarning'>\n",
      "<class 'pkg_resources.PkgResourcesDeprecationWarning'>\n",
      "<class 'warnings._OptionError'>\n",
      "<class 'runpy._Error'>\n",
      "<class 're.error'>\n",
      "<class 'sre_parse.Verbose'>\n",
      "<class 'locale.Error'>\n",
      "<class 'subprocess.SubprocessError'>\n",
      "<class 'subprocess.CalledProcessError'>\n",
      "<class 'subprocess.TimeoutExpired'>\n",
      "<class 'tokenize.TokenError'>\n",
      "<class 'tokenize.StopTokenizing'>\n",
      "<class 'inspect.ClassFoundException'>\n",
      "<class 'inspect.EndOfBlock'>\n",
      "<class 'traitlets.traitlets.TraitError'>\n",
      "<class 'copy.Error'>\n",
      "<class 'concurrent.futures._base.Error'>\n",
      "<class 'concurrent.futures._base.CancelledError'>\n",
      "<class 'concurrent.futures._base.TimeoutError'>\n",
      "<class 'concurrent.futures._base.InvalidStateError'>\n",
      "<class 'socket._GiveupOnSendfile'>\n",
      "<class 'struct.error'>\n",
      "<class 'binascii.Incomplete'>\n",
      "<class 'asyncio.exceptions.TimeoutError'>\n",
      "<class 'asyncio.exceptions.InvalidStateError'>\n",
      "<class 'asyncio.exceptions.LimitOverrunError'>\n",
      "<class 'asyncio.queues.QueueEmpty'>\n",
      "<class 'asyncio.queues.QueueFull'>\n",
      "<class '_queue.Empty'>\n",
      "<class 'queue.Full'>\n",
      "<class 'ctypes.ArgumentError'>\n",
      "<class 'zmq.error.ZMQBaseError'>\n",
      "<class 'zmq.error.ZMQError'>\n",
      "<class 'zmq.error.ContextTerminated'>\n",
      "<class 'zmq.error.Again'>\n",
      "<class 'zmq.error.InterruptedSystemCall'>\n",
      "<class 'zmq.error.ZMQBindError'>\n",
      "<class 'zmq.error.NotDone'>\n",
      "<class '_pickle.PickleError'>\n",
      "<class '_pickle.PicklingError'>\n",
      "<class '_pickle.UnpicklingError'>\n",
      "<class 'pickle._Stop'>\n",
      "<class 'argparse.ArgumentError'>\n",
      "<class 'argparse.ArgumentTypeError'>\n",
      "<class 'traitlets.config.loader.ConfigError'>\n",
      "<class 'traitlets.config.loader.ConfigLoaderError'>\n",
      "<class 'traitlets.config.loader.ArgumentError'>\n",
      "<class 'traitlets.config.loader.ConfigFileNotFound'>\n",
      "<class 'traitlets.config.configurable.ConfigurableError'>\n",
      "<class 'traitlets.config.configurable.MultipleInstanceError'>\n",
      "<class 'traitlets.config.application.ApplicationError'>\n",
      "<class 'zlib.error'>\n",
      "<class 'tornado.util.TimeoutError'>\n",
      "<class '_curses.error'>\n",
      "<class 'tornado.concurrent.ReturnValueIgnoredError'>\n",
      "<class 'tornado.gen.KeyReuseError'>\n",
      "<class 'tornado.gen.UnknownKeyError'>\n",
      "<class 'tornado.gen.LeakedCallbackError'>\n",
      "<class 'tornado.gen.BadYieldError'>\n",
      "<class 'tornado.gen.ReturnValueIgnoredError'>\n",
      "<class 'tornado.gen.Return'>\n",
      "<class 'jupyter_client.channels.InvalidPortNumber'>\n",
      "<class 'termios.error'>\n",
      "<class '_lzma.LZMAError'>\n",
      "<class 'shutil.RegistryError'>\n",
      "<class 'shutil._GiveupOnFastCopy'>\n",
      "<class 'configparser.Error'>\n",
      "<class 'configparser.NoSectionError'>\n",
      "<class 'configparser.DuplicateSectionError'>\n",
      "<class 'configparser.DuplicateOptionError'>\n",
      "<class 'configparser.NoOptionError'>\n",
      "<class 'configparser.InterpolationError'>\n",
      "<class 'configparser.InterpolationMissingOptionError'>\n",
      "<class 'configparser.InterpolationSyntaxError'>\n",
      "<class 'configparser.InterpolationDepthError'>\n",
      "<class 'configparser.ParsingError'>\n",
      "<class 'configparser.MissingSectionHeaderError'>\n",
      "<class 'jupyter_client.localinterfaces.NoIPAddresses'>\n",
      "<class 'zipfile.BadZipFile'>\n",
      "<class 'zipfile.LargeZipFile'>\n",
      "<class 'entrypoints.BadEntryPoint'>\n",
      "<class 'entrypoints.NoSuchEntryPoint'>\n",
      "<class 'jupyter_client.multikernelmanager.DuplicateKernelError'>\n",
      "<class 'pydoc.ErrorDuringImport'>\n",
      "<class 'executing.executing.NotOneValueFound'>\n",
      "<class 'pure_eval.utils.CannotEval'>\n",
      "<class 'pygments.util.OptionError'>\n",
      "<class 'bdb.BdbQuit'>\n",
      "<class 'pdb.Restart'>\n",
      "<class 'pexpect.exceptions.ExceptionPexpect'>\n",
      "<class 'pexpect.exceptions.EOF'>\n",
      "<class 'pexpect.exceptions.TIMEOUT'>\n",
      "<class 'ptyprocess.util.PtyProcessError'>\n",
      "<class 'IPython.utils.process.FindCmdError'>\n",
      "<class 'IPython.utils.path.HomeDirError'>\n",
      "<class 'IPython.core.profiledir.ProfileDirError'>\n",
      "<class 'IPython.core.error.IPythonCoreError'>\n",
      "<class 'IPython.core.error.TryNext'>\n",
      "<class 'IPython.core.error.UsageError'>\n",
      "<class 'IPython.core.error.StdinNotImplementedError'>\n",
      "<class 'IPython.core.error.InputRejected'>\n",
      "<class 'getopt.GetoptError'>\n",
      "<class 'pygments.filters.ErrorToken'>\n",
      "<class 'IPython.core.prefilter.PrefilterError'>\n",
      "<class 'IPython.core.alias.AliasError'>\n",
      "<class 'IPython.core.alias.InvalidAliasError'>\n",
      "<class 'sqlite3.Error'>\n",
      "<class 'sqlite3.InterfaceError'>\n",
      "<class 'sqlite3.DatabaseError'>\n",
      "<class 'sqlite3.InternalError'>\n",
      "<class 'sqlite3.OperationalError'>\n",
      "<class 'sqlite3.ProgrammingError'>\n",
      "<class 'sqlite3.IntegrityError'>\n",
      "<class 'sqlite3.DataError'>\n",
      "<class 'sqlite3.NotSupportedError'>\n",
      "<class 'sqlite3.Warning'>\n",
      "<class 'IPython.core.interactiveshell.SpaceInInput'>\n",
      "<class 'xml.dom.DOMException'>\n",
      "<class 'xml.dom.IndexSizeErr'>\n",
      "<class 'xml.dom.DomstringSizeErr'>\n",
      "<class 'xml.dom.HierarchyRequestErr'>\n",
      "<class 'xml.dom.WrongDocumentErr'>\n",
      "<class 'xml.dom.InvalidCharacterErr'>\n",
      "<class 'xml.dom.NoDataAllowedErr'>\n",
      "<class 'xml.dom.NoModificationAllowedErr'>\n",
      "<class 'xml.dom.NotFoundErr'>\n",
      "<class 'xml.dom.NotSupportedErr'>\n",
      "<class 'xml.dom.InuseAttributeErr'>\n",
      "<class 'xml.dom.InvalidStateErr'>\n",
      "<class 'xml.dom.SyntaxErr'>\n",
      "<class 'xml.dom.InvalidModificationErr'>\n",
      "<class 'xml.dom.NamespaceErr'>\n",
      "<class 'xml.dom.InvalidAccessErr'>\n",
      "<class 'xml.dom.ValidationErr'>\n",
      "<class 'prompt_toolkit.validation.ValidationError'>\n",
      "<class 'prompt_toolkit.buffer.EditReadOnlyBuffer'>\n",
      "<class 'prompt_toolkit.buffer._Retry'>\n",
      "<class 'prompt_toolkit.layout.layout.InvalidLayoutError'>\n",
      "<class 'prompt_toolkit.renderer.HeightIsUnknownError'>\n",
      "<class 'parso.parser.ParserSyntaxError'>\n",
      "<class 'parso.parser.InternalParseError'>\n",
      "<class 'parso.python.diff._PositionUpdatingFinished'>\n",
      "<class 'jedi.inference.helpers.SimpleGetItemNotFound'>\n",
      "<class 'jedi.inference.utils.UncaughtAttributeError'>\n",
      "<class 'jedi.inference.base_value.HasNoContext'>\n",
      "<class 'jedi.inference.arguments.ParamIssue'>\n",
      "<class 'jedi.api.exceptions._JediError'>\n",
      "<class 'jedi.api.exceptions.InternalError'>\n",
      "<class 'jedi.api.exceptions.WrongVersion'>\n",
      "<class 'jedi.api.exceptions.RefactoringError'>\n",
      "<class 'jedi.api.helpers.OnErrorLeaf'>\n",
      "<class 'jedi.api.environment.InvalidPythonEnvironment'>\n",
      "<class 'email.errors.MessageError'>\n",
      "<class 'email.errors.MessageParseError'>\n",
      "<class 'email.errors.HeaderParseError'>\n",
      "<class 'email.errors.BoundaryError'>\n",
      "<class 'email.errors.MultipartConversionError'>\n",
      "<class 'email.errors.CharsetError'>\n",
      "<class 'uu.Error'>\n",
      "<class 'http.client.HTTPException'>\n",
      "<class 'http.client.NotConnected'>\n",
      "<class 'http.client.InvalidURL'>\n",
      "<class 'http.client.UnknownProtocol'>\n",
      "<class 'http.client.UnknownTransferEncoding'>\n",
      "<class 'http.client.UnimplementedFileMode'>\n",
      "<class 'http.client.IncompleteRead'>\n",
      "<class 'http.client.ImproperConnectionState'>\n",
      "<class 'http.client.CannotSendRequest'>\n",
      "<class 'http.client.CannotSendHeader'>\n",
      "<class 'http.client.ResponseNotReady'>\n",
      "<class 'http.client.BadStatusLine'>\n",
      "<class 'http.client.RemoteDisconnected'>\n",
      "<class 'http.client.LineTooLong'>\n",
      "<class 'IPython.core.magics.code.InteractivelyDefined'>\n",
      "<class 'IPython.terminal.embed.KillEmbedded'>\n",
      "<class 'psutil.Error'>\n",
      "<class 'psutil.NoSuchProcess'>\n",
      "<class 'psutil.ZombieProcess'>\n",
      "<class 'psutil.AccessDenied'>\n",
      "<class 'psutil.TimeoutExpired'>\n",
      "<class 'psutil._pslinux._Ipv6UnsupportedError'>\n",
      "<class 'tornado.queues.QueueEmpty'>\n",
      "<class 'tornado.queues.QueueFull'>\n",
      "<class '_pydev_bundle._pydev_saved_modules.DebuggerInitializationError'>\n",
      "<class 'xml.parsers.expat.ExpatError'>\n",
      "<class 'xmlrpc.client.Error'>\n",
      "<class 'xmlrpc.client.ProtocolError'>\n",
      "<class 'xmlrpc.client.ResponseError'>\n",
      "<class 'xmlrpc.client.Fault'>\n",
      "<class 'pkg_resources._vendor.pyparsing.exceptions.ParseBaseException'>\n",
      "<class 'pkg_resources._vendor.pyparsing.exceptions.ParseException'>\n",
      "<class 'pkg_resources._vendor.pyparsing.exceptions.ParseFatalException'>\n",
      "<class 'pkg_resources._vendor.pyparsing.exceptions.ParseSyntaxException'>\n",
      "<class 'pkg_resources._vendor.pyparsing.exceptions.RecursiveGrammarException'>\n",
      "<class 'pkg_resources.ResolutionError'>\n",
      "<class 'pkg_resources.VersionConflict'>\n",
      "<class 'pkg_resources.ContextualVersionConflict'>\n",
      "<class 'pkg_resources.DistributionNotFound'>\n",
      "<class 'pkg_resources.UnknownExtra'>\n",
      "<class '_pydevd_bundle.pydevd_runpy._Error'>\n",
      "<class '_pydevd_bundle.pydevd_resolver.UnableToResolveVariableException'>\n",
      "<class '_pydev_bundle.pydev_monkey.InvalidTypeInArgsException'>\n"
     ]
    }
   ],
   "source": [
    "def hierarchy(exception_class):\n",
    "    print(exception_class)\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        hierarchy(subclass)\n",
    "\n",
    "hierarchy(Exception)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "1c348072",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception\n",
      "TypeError\n",
      "FloatOperation\n",
      "MultipartConversionError\n",
      "StopAsyncIteration\n",
      "StopIteration\n",
      "ImportError\n",
      "ModuleNotFoundError\n",
      "ZipImportError\n",
      "OSError\n",
      "ConnectionError\n",
      "BrokenPipeError\n",
      "ConnectionAbortedError\n",
      "ConnectionRefusedError\n",
      "ConnectionResetError\n",
      "RemoteDisconnected\n",
      "BlockingIOError\n",
      "ChildProcessError\n",
      "FileExistsError\n",
      "FileNotFoundError\n",
      "IsADirectoryError\n",
      "NotADirectoryError\n",
      "InterruptedError\n",
      "InterruptedSystemCall\n",
      "PermissionError\n",
      "ProcessLookupError\n",
      "TimeoutError\n",
      "UnsupportedOperation\n",
      "itimer_error\n",
      "herror\n",
      "gaierror\n",
      "SSLError\n",
      "SSLCertVerificationError\n",
      "SSLZeroReturnError\n",
      "SSLWantWriteError\n",
      "SSLWantReadError\n",
      "SSLSyscallError\n",
      "SSLEOFError\n",
      "Error\n",
      "SameFileError\n",
      "SpecialFileError\n",
      "ExecError\n",
      "ReadError\n",
      "URLError\n",
      "HTTPError\n",
      "ContentTooShortError\n",
      "BadGzipFile\n",
      "EOFError\n",
      "IncompleteReadError\n",
      "RuntimeError\n",
      "RecursionError\n",
      "NotImplementedError\n",
      "ZMQVersionError\n",
      "StdinNotImplementedError\n",
      "_DeadlockError\n",
      "BrokenBarrierError\n",
      "BrokenExecutor\n",
      "BrokenThreadPool\n",
      "SendfileNotAvailableError\n",
      "ExtractionError\n",
      "VariableError\n",
      "NameError\n",
      "UnboundLocalError\n",
      "AttributeError\n",
      "FrozenInstanceError\n",
      "SyntaxError\n",
      "IndentationError\n",
      "TabError\n",
      "LookupError\n",
      "IndexError\n",
      "KeyError\n",
      "NoSuchKernel\n",
      "UnknownBackend\n",
      "CodecRegistryError\n",
      "ValueError\n",
      "UnicodeError\n",
      "UnicodeEncodeError\n",
      "UnicodeDecodeError\n",
      "UnicodeTranslateError\n",
      "UnsupportedOperation\n",
      "JSONDecodeError\n",
      "SSLCertVerificationError\n",
      "Error\n",
      "UnsupportedDigestmodError\n",
      "IllegalMonthError\n",
      "IllegalWeekdayError\n",
      "ParserError\n",
      "ClassNotFound\n",
      "ClipboardEmpty\n",
      "MessageDefect\n",
      "NoBoundaryInMultipartDefect\n",
      "StartBoundaryNotFoundDefect\n",
      "CloseBoundaryNotFoundDefect\n",
      "FirstHeaderLineIsContinuationDefect\n",
      "MisplacedEnvelopeHeaderDefect\n",
      "MissingHeaderBodySeparatorDefect\n",
      "MultipartInvariantViolationDefect\n",
      "InvalidMultipartContentTransferEncodingDefect\n",
      "UndecodableBytesDefect\n",
      "InvalidBase64PaddingDefect\n",
      "InvalidBase64CharactersDefect\n",
      "InvalidBase64LengthDefect\n",
      "HeaderDefect\n",
      "InvalidHeaderDefect\n",
      "HeaderMissingRequiredValue\n",
      "NonPrintableDefect\n",
      "ObsoleteHeaderDefect\n",
      "NonASCIILocalPartDefect\n",
      "InvalidDateDefect\n",
      "MacroToEdit\n",
      "InvalidFileException\n",
      "UnequalIterablesError\n",
      "InvalidVersion\n",
      "_InvalidELFFileHeader\n",
      "InvalidWheelFilename\n",
      "InvalidSdistFilename\n",
      "InvalidSpecifier\n",
      "InvalidMarker\n",
      "UndefinedComparison\n",
      "UndefinedEnvironmentName\n",
      "InvalidRequirement\n",
      "RequirementParseError\n",
      "InvalidVersion\n",
      "AssertionError\n",
      "ArithmeticError\n",
      "FloatingPointError\n",
      "OverflowError\n",
      "ZeroDivisionError\n",
      "DivisionByZero\n",
      "DivisionUndefined\n",
      "DecimalException\n",
      "Clamped\n",
      "Rounded\n",
      "Underflow\n",
      "Overflow\n",
      "Inexact\n",
      "Underflow\n",
      "Overflow\n",
      "Subnormal\n",
      "Underflow\n",
      "DivisionByZero\n",
      "FloatOperation\n",
      "InvalidOperation\n",
      "ConversionSyntax\n",
      "DivisionImpossible\n",
      "DivisionUndefined\n",
      "InvalidContext\n",
      "SystemError\n",
      "CodecRegistryError\n",
      "ReferenceError\n",
      "MemoryError\n",
      "BufferError\n",
      "Warning\n",
      "UserWarning\n",
      "GetPassWarning\n",
      "FormatterWarning\n",
      "EncodingWarning\n",
      "DeprecationWarning\n",
      "ProvisionalWarning\n",
      "PendingDeprecationWarning\n",
      "SyntaxWarning\n",
      "RuntimeWarning\n",
      "ProactorSelectorThreadWarning\n",
      "UnknownTimezoneWarning\n",
      "PEP440Warning\n",
      "FutureWarning\n",
      "ProvisionalCompleterWarning\n",
      "ImportWarning\n",
      "UnicodeWarning\n",
      "BytesWarning\n",
      "ResourceWarning\n",
      "DeprecatedTzFormatWarning\n",
      "PkgResourcesDeprecationWarning\n",
      "_OptionError\n",
      "_Error\n",
      "error\n",
      "Verbose\n",
      "Error\n",
      "SubprocessError\n",
      "CalledProcessError\n",
      "TimeoutExpired\n",
      "TokenError\n",
      "StopTokenizing\n",
      "ClassFoundException\n",
      "EndOfBlock\n",
      "TraitError\n",
      "Error\n",
      "Error\n",
      "CancelledError\n",
      "TimeoutError\n",
      "InvalidStateError\n",
      "_GiveupOnSendfile\n",
      "error\n",
      "Incomplete\n",
      "TimeoutError\n",
      "InvalidStateError\n",
      "LimitOverrunError\n",
      "QueueEmpty\n",
      "QueueFull\n",
      "Empty\n",
      "Full\n",
      "ArgumentError\n",
      "ZMQBaseError\n",
      "ZMQError\n",
      "ContextTerminated\n",
      "Again\n",
      "InterruptedSystemCall\n",
      "ZMQBindError\n",
      "NotDone\n",
      "PickleError\n",
      "PicklingError\n",
      "UnpicklingError\n",
      "_Stop\n",
      "ArgumentError\n",
      "ArgumentTypeError\n",
      "ConfigError\n",
      "ConfigLoaderError\n",
      "ArgumentError\n",
      "ConfigFileNotFound\n",
      "ConfigurableError\n",
      "MultipleInstanceError\n",
      "ApplicationError\n",
      "error\n",
      "TimeoutError\n",
      "error\n",
      "ReturnValueIgnoredError\n",
      "KeyReuseError\n",
      "UnknownKeyError\n",
      "LeakedCallbackError\n",
      "BadYieldError\n",
      "ReturnValueIgnoredError\n",
      "Return\n",
      "InvalidPortNumber\n",
      "error\n",
      "LZMAError\n",
      "RegistryError\n",
      "_GiveupOnFastCopy\n",
      "Error\n",
      "NoSectionError\n",
      "DuplicateSectionError\n",
      "DuplicateOptionError\n",
      "NoOptionError\n",
      "InterpolationError\n",
      "InterpolationMissingOptionError\n",
      "InterpolationSyntaxError\n",
      "InterpolationDepthError\n",
      "ParsingError\n",
      "MissingSectionHeaderError\n",
      "NoIPAddresses\n",
      "BadZipFile\n",
      "LargeZipFile\n",
      "BadEntryPoint\n",
      "NoSuchEntryPoint\n",
      "DuplicateKernelError\n",
      "ErrorDuringImport\n",
      "NotOneValueFound\n",
      "CannotEval\n",
      "OptionError\n",
      "BdbQuit\n",
      "Restart\n",
      "ExceptionPexpect\n",
      "EOF\n",
      "TIMEOUT\n",
      "PtyProcessError\n",
      "FindCmdError\n",
      "HomeDirError\n",
      "ProfileDirError\n",
      "IPythonCoreError\n",
      "TryNext\n",
      "UsageError\n",
      "StdinNotImplementedError\n",
      "InputRejected\n",
      "GetoptError\n",
      "ErrorToken\n",
      "PrefilterError\n",
      "AliasError\n",
      "InvalidAliasError\n",
      "Error\n",
      "InterfaceError\n",
      "DatabaseError\n",
      "InternalError\n",
      "OperationalError\n",
      "ProgrammingError\n",
      "IntegrityError\n",
      "DataError\n",
      "NotSupportedError\n",
      "Warning\n",
      "SpaceInInput\n",
      "DOMException\n",
      "IndexSizeErr\n",
      "DomstringSizeErr\n",
      "HierarchyRequestErr\n",
      "WrongDocumentErr\n",
      "InvalidCharacterErr\n",
      "NoDataAllowedErr\n",
      "NoModificationAllowedErr\n",
      "NotFoundErr\n",
      "NotSupportedErr\n",
      "InuseAttributeErr\n",
      "InvalidStateErr\n",
      "SyntaxErr\n",
      "InvalidModificationErr\n",
      "NamespaceErr\n",
      "InvalidAccessErr\n",
      "ValidationErr\n",
      "ValidationError\n",
      "EditReadOnlyBuffer\n",
      "_Retry\n",
      "InvalidLayoutError\n",
      "HeightIsUnknownError\n",
      "ParserSyntaxError\n",
      "InternalParseError\n",
      "_PositionUpdatingFinished\n",
      "SimpleGetItemNotFound\n",
      "UncaughtAttributeError\n",
      "HasNoContext\n",
      "ParamIssue\n",
      "_JediError\n",
      "InternalError\n",
      "WrongVersion\n",
      "RefactoringError\n",
      "OnErrorLeaf\n",
      "InvalidPythonEnvironment\n",
      "MessageError\n",
      "MessageParseError\n",
      "HeaderParseError\n",
      "BoundaryError\n",
      "MultipartConversionError\n",
      "CharsetError\n",
      "Error\n",
      "HTTPException\n",
      "NotConnected\n",
      "InvalidURL\n",
      "UnknownProtocol\n",
      "UnknownTransferEncoding\n",
      "UnimplementedFileMode\n",
      "IncompleteRead\n",
      "ImproperConnectionState\n",
      "CannotSendRequest\n",
      "CannotSendHeader\n",
      "ResponseNotReady\n",
      "BadStatusLine\n",
      "RemoteDisconnected\n",
      "LineTooLong\n",
      "InteractivelyDefined\n",
      "KillEmbedded\n",
      "Error\n",
      "NoSuchProcess\n",
      "ZombieProcess\n",
      "AccessDenied\n",
      "TimeoutExpired\n",
      "_Ipv6UnsupportedError\n",
      "QueueEmpty\n",
      "QueueFull\n",
      "DebuggerInitializationError\n",
      "ExpatError\n",
      "Error\n",
      "ProtocolError\n",
      "ResponseError\n",
      "Fault\n",
      "ParseBaseException\n",
      "ParseException\n",
      "ParseFatalException\n",
      "ParseSyntaxException\n",
      "RecursiveGrammarException\n",
      "ResolutionError\n",
      "VersionConflict\n",
      "ContextualVersionConflict\n",
      "DistributionNotFound\n",
      "UnknownExtra\n",
      "_Error\n",
      "UnableToResolveVariableException\n",
      "InvalidTypeInArgsException\n"
     ]
    }
   ],
   "source": [
    "def hierarchy(exception_class):\n",
    "    print(exception_class.__name__)\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        hierarchy(subclass)\n",
    "\n",
    "hierarchy(Exception)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9ad298c6",
   "metadata": {},
   "source": [
    "Q3. What errors are defined in the ArithmeticError class? Explain any two with an example."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "448fc61e",
   "metadata": {},
   "source": [
    "The ArithmeticError class is a subclass of the Exception class in Python and is used to indicate errors related to arithmetic operations.\n",
    "Some of the errors are:"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "73fe948d",
   "metadata": {},
   "source": [
    "1. ZeroDivisionError: This error is raised when you try to divide a number by zero"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "baf20802",
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[5], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;241;43m2\u001b[39;49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[38;5;241;43m0\u001b[39;49m\n",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "2/0"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d876d399",
   "metadata": {},
   "source": [
    "2. OverflowError: This error is raised when an arithmetic operation results in a number that is too large to be represented"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "11d4ac5c",
   "metadata": {},
   "outputs": [
    {
     "ename": "OverflowError",
     "evalue": "math range error",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mOverflowError\u001b[0m                             Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[6], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mmath\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[43mmath\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexp\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m1000\u001b[39;49m\u001b[43m)\u001b[49m)\n",
      "\u001b[0;31mOverflowError\u001b[0m: math range error"
     ]
    }
   ],
   "source": [
    "import math\n",
    "print(math.exp(1000))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "08a84982",
   "metadata": {},
   "source": [
    "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "34f90980",
   "metadata": {},
   "source": [
    "LookupError class in python is subclass of the Exception class, and it is used to indicate an error which occur when a value for which we are looking for in not present in the data structure"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3d7bbe29",
   "metadata": {},
   "source": [
    "1. KeyError : it is raised when you access a dictionary key that doesn't exist. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "3c3bbea1",
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "'d'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[7], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m# example:\u001b[39;00m\n\u001b[1;32m      2\u001b[0m dic\u001b[38;5;241m=\u001b[39m{\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124ma\u001b[39m\u001b[38;5;124m\"\u001b[39m:\u001b[38;5;241m1\u001b[39m,\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mb\u001b[39m\u001b[38;5;124m\"\u001b[39m:\u001b[38;5;241m2\u001b[39m}\n\u001b[0;32m----> 3\u001b[0m \u001b[43mdic\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43md\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m]\u001b[49m\n",
      "\u001b[0;31mKeyError\u001b[0m: 'd'"
     ]
    }
   ],
   "source": [
    "# example:\n",
    "dic={\"a\":1,\"b\":2}\n",
    "dic[\"d\"]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "352baa0e",
   "metadata": {},
   "source": [
    "2. IndexError: This error is raised when you try to access a list index that is out of range."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "9f23ac22",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[8], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m lst\u001b[38;5;241m=\u001b[39m[\u001b[38;5;241m1\u001b[39m,\u001b[38;5;241m2\u001b[39m,\u001b[38;5;241m3\u001b[39m,\u001b[38;5;241m4\u001b[39m]\n\u001b[0;32m----> 2\u001b[0m \u001b[43mlst\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m8\u001b[39;49m\u001b[43m]\u001b[49m\n",
      "\u001b[0;31mIndexError\u001b[0m: list index out of range"
     ]
    }
   ],
   "source": [
    "lst=[1,2,3,4]\n",
    "lst[8]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1e8ae223",
   "metadata": {},
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6019c6a2",
   "metadata": {},
   "source": [
    "ImportError is a class of exceptions in Python that is raised when an import statement fails."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "aca0d6c9",
   "metadata": {},
   "source": [
    "it can occur if:\n",
    "\n",
    "    1. the module imported doesn't exist in list of directories.\n",
    "    2. the module imported depends on another module that could not be imported"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "29eeab3b",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'Gravity'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[9], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m#example:\u001b[39;00m\n\u001b[0;32m----> 3\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mGravity\u001b[39;00m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'Gravity'"
     ]
    }
   ],
   "source": [
    "#example:\n",
    "\n",
    "import Gravity"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6e9912d6",
   "metadata": {},
   "source": [
    "Q6. List down some best practices for exception handling in python."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "43054a6a",
   "metadata": {},
   "source": [
    "1.  Catch exceptions as narrowly as possible: Instead of catching a broad exception like Exception, catch only the exceptions that you know how to handle."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e770b494",
   "metadata": {},
   "source": [
    "2. Avoid catching too many exceptions: It is generally best to only catch exceptions that you know how to handle. If you catch too many exceptions, you may hide programming errors or bugs that would otherwise be more easily detected."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1fb508d1",
   "metadata": {},
   "source": [
    "3. Use the built-in logging module for logging exceptions: The built-in logging module is a powerful tool for logging information about errors and other events in your application. Use it to log exceptions and other errors so that you can diagnose problems more easily."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2499a385",
   "metadata": {},
   "source": [
    "4. When raising an exception, provide a meaningful error message that explains the problem. This will make it easier for other developers to understand what went wrong, and it will make debugging easier in case of an error."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "36b498ac",
   "metadata": {},
   "source": [
    "5. Don't catch exceptions that you can't handle: If you catch an exception and don't know how to handle it, it is better to simply propagate the exception up the call stack rather than catch and ignore it."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9100eae9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
